# Generated by Django 3.2.8 on 2021-10-15 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_sport', models.CharField(max_length=15)),
                ('weigth', models.FloatField(null=True)),
                ('heigth', models.IntegerField(null=True)),
                ('ftp', models.IntegerField(null=True)),
                ('max_hr', models.IntegerField(null=True)),
                ('hr_zones', models.CharField(max_length=50)),
                ('pw_zones', models.CharField(max_length=50)),
                ('lactate_thr', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
