# Generated by Django 3.2.8 on 2021-10-25 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_diary_api', '0002_healthdiary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 25)),
        ),
    ]
