# Generated by Django 3.2.8 on 2021-10-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_diary_api', '0005_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdiary',
            old_name='moring_mood',
            new_name='morning_mood',
        ),
    ]
